os: linux
dist: trusty
language: java
sudo: required
before_install:
 #Megacmd required ubuntu packages
 - sudo apt-get -y install libc-ares2 libcrypto++9 libmediainfo0 libzen0
 #Install Megacmd
 - wget https://mega.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megacmd-xUbuntu_14.04_amd64.deb
 - sudo dpkg -i ./megacmd-xUbuntu_14.04_amd64.deb
 - mega-version
 - mega-help
before_deploy:
 #GPG keys
 - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
 - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
 - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
 - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: target/megacmd4j-$project_version.jar
  skip_cleanup: true
  on:
    tags: true
after_deploy:
#After running make release a release tag is created.
#Then run this script and a release artifact is
#uploaded to the Maven Central
 - make deploy
