language: java
cache: megaCmd
sudo: enabled
before_install:
 #Megacmd required ubuntu packages
 - sudo apt-get -y install libc-ares2 libcrypto++9 libmediainfo0 libzen0
 #Install Megacmd
 - wget https://mega.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megacmd-xUbuntu_14.04_amd64.deb
 - sudo dpkg -i ./megacmd-xUbuntu_14.04_amd64.deb
 - mega-help
