language: java
matrix:
    include:
        - os: linux
          dist: xenial
          language: java
        - os: osx
          osx_image: xcode9.3
sudo: required
before_install:
 -  ./.travis/before_install.sh
 - mega-version
 - mega-help
before_deploy:
 -  ./.travis/before_deploy.sh
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: target/megacmd4j-$PROJECT_VERSION.jar
  skip_cleanup: true
  on:
    tags: true
after_deploy:
#After running make release a release tag is created.
#Then run this script and a release artifact is
#uploaded to the Maven Central
 - make deploy
