language: java
cache:
  directories:
    - $HOME/.megaCmd
sudo: enabled
before_install:
 #Megacmd required ubuntu packages
 - sudo apt-get -y install libc-ares2 libcrypto++9 libmediainfo0 libzen0
 #Install Megacmd
 - wget https://mega.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megacmd-xUbuntu_14.04_amd64.deb
 - sudo dpkg -i ./megacmd-xUbuntu_14.04_amd64.deb
 - mega-help
install:
     mvn  --settings .travis/maven-settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_deploy:
 - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
 - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
deploy:
  provider: script
  #After running release:clean release:prepare
  #A release tag is created and this script is run
  #And a release artifact is uploaded to the Maven Central
  script: "mvn clean deploy --settings .travis/maven-settings.xml -DskipTests=true -B -U"
  skip_cleanup: true
  on:
    tags: true
