language: java
sudo: enabled
env:
  global:
  - secure: grqHTNZoRUlil2FTbrYjRmmkL7OKDRpoF0KIIQqpk9izr2qN3zqKV+SMPWo3Vt1ACYX4LmA3WrkPjy/yhCZ/kMzYPOqW8Mg5kdI96dhi05J69Uqx7vaLKUW+ci95NxHd9X1L2d77QwX3h58uG5QTQJh8c4+psRVp8lmVZhFmqYn8UwgSuUkc/Wq3VpmsnjfDrptEKUxfXdVNgIT04DNynzA21hxLMNaZEAszi/a1WqxDqcfveVyVaUnfJHnsoJab136frjXFjAVJWFHsN6oCYwPasFzko4ssgGlxQOLCtrKhcAu1iu9MO+3y9g1Vz66Op6kgzBw95K+C6n7GPuDW4dfeV8+T+n6zEluL2CX3gAzaSqNF7eW+ct3izPX2+Ji8+WsI+pRx5Bcim6vOa1aDfScGFaqWWv/XqPpzKRbCc0idKOBDmpk09zVtlpgHFRJ6FwINWtu9MilwymnGUPmVpvNHgPolPOh/O4qqLZwADiQN3IQPnJxQ8pts9DPMVn7v4QYGCbx/QNsPw3ALGXGZCC1CT3e30/yLxL/6DN4eJBIEvlpkRXBWu8OLVe53G4Rh0PnT9v8uwSbaF/IX5c/hbiq3ZJi9LDcmH+XZnCoDUi6KT3qpXyD74J+gsJMZ5H0VIIbGm0mWRO95wCWjG56kXIB73v8v0Br3Iui5pAHnm9Q=
  - secure: E8nc0Cw7C8M8a3AAimjPZIKkr5P2dcfJYiuxfHnHNsRyzoWNtfhmmMebJ7z5k89qG5LhR73nwpwtsbMctqJXDfGEtQPoOJjlxeYwmwD98ME3YxHFF2Wtpr/0nsCUGsJhLzqUXHvEm6597Xug0aiZNiw7jb9FYzpeWwT2f052FRDHIdMJtrzuvr6hzTvMJ5/59foiOEgLZ+m6D/nKvk/gb3+h9/UJvIVVtzNw/O0kX1o6s6BtiVrpVOX5u4kX6XO6OR1YG+AGEtTHGyJFpsx5nPvPIDQJt4lEYSAwioBB6BfdNWrMfOOnde7nMUS3Gu0hF0wdYHuOEXJKWn/6ovxfbEve8qreZVtY7X0sokykBPgO4uHOigPINBnMaJH8WAo9KbquE5rlzq9mTzxHlF4YJcJIdcbk2s/lkaTKv02dKgwz5cOp6oDerlPT28lzn5IxKRqMJSLRZ5rgcPm0gZQzhUgfvd6yGYFrf8BI3XwgSJJJNLcBmURGfLRZZtCtn768WxLYRQtW8WVP6DfBi4bQDf5z1pqaYUNFZ9CL5lyAC0eDBxhJccvmmIX/DsP/alw4ixpPP7tDh2VTvhaKk+AH0m7NkJN+xGRLikCqLSQAVDnph76nHBDAZS6tkXExt/RlmbSjRBLNarBhgqH97gJH5Z+TghkgDSK5piSvReozbC8=
before_install:
 #Config package installation
 - sudo dpkg --configure -a --force-depends
 - sudo apt-get -f install
 #Install Megacmd
 - wget https://mega.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megacmd-xUbuntu_14.04_amd64.deb
 - sudo dpkg -i ./megacmd-xUbuntu_14.04_amd64.deb
 - MegaClient help
