language: java
cache:
  directories:
    - $HOME/.megaCmd
sudo: enabled
before_install:
 #Megacmd required ubuntu packages
 - sudo apt-get -y install libc-ares2 libcrypto++9 libmediainfo0 libzen0
 #Install Megacmd
 - wget https://mega.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megacmd-xUbuntu_14.04_amd64.deb
 - sudo dpkg -i ./megacmd-xUbuntu_14.04_amd64.deb
 - mega-help
before_deploy:
 - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
 - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
deploy:
  provider: script
  script: "mvn --settings .travis/maven-settings.xml deploy"
  skip_cleanup: true
  on:
    tags: true
